version: "3.9"

volumes:
  postgres_data:

name: hpds
services:
  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .envs/postgres/.env
    ports:
    - 5432:5432
    # healthcheck:
    #   test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
    #   interval: 2s
    #   timeout: 5s
    #   retries: 5
  rabbitmq:
    image: rabbitmq:3.12
    env_file:
      - .envs/rabbitmq/.env
    ports:
    - 5672:5672
    - 15672:15672