version: "3.9"
# TODO: Remove additional ports before deployment
volumes:
  postgres_data:

name: hpds
services:
  apigateway:
    build:
      context: .
      dockerfile: apigateway/Dockerfile
    ports:
    - 8000:80
    depends_on:
      rabbitmq:
        condition: service_healthy

  userservice:
    build:
      context: .
      dockerfile: userservice/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  reservationservice:
    build:
      context: .
      dockerfile: reservationservice/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  hotelservice:
    build:
      context: .
      dockerfile: hotelservice/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  paymentservice:
    build:
      context: .
      dockerfile: paymentservice/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy


  transportservice:
      build:
        context: .
        dockerfile: transportservice/Dockerfile
      depends_on:
        rabbitmq:
          condition: service_healthy
        postgres:
          condition: service_healthy

  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .envs/postgres/.env
    ports:
    - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d userservice_db']
      interval: 2s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12
    env_file:
      - .envs/rabbitmq/.env
    ports:
    - 5672:5672
    - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 2s
      timeout: 10s
      retries: 5
