version: "3.9"

services:
  front:
    image: kepins/rsww_184297_front:v4.0.0
    ports:
      - 18460:80
    depends_on:
      - apigateway
  apigateway:
    image: kepins/rsww_184297_apigateway:v4.0.0
    env_file:
      - .envs.production/apigateway/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
  userservice:
    image: kepins/rsww_184297_userservice:v4.0.0
    env_file:
      - .envs.production/userservice/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
  reservationservice:
    image: kepins/rsww_184297_reservationservice:v4.0.0
    env_file:
      - .envs.production/reservationservice/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
  hotelservice:
    image: kepins/rsww_184297_hotelservice:v4.0.0
    env_file:
      - .envs.production/hotelservice/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
  transportservice:
    image: kepins/rsww_184297_transportservice:v4.0.0
    env_file:
      - .envs.production/transportservice/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
  paymentservice:
    image: kepins/rsww_184297_paymentservice:v4.0.0
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .envs.production/postgres/.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d userservice_db']
      interval: 2s
      timeout: 10s
      retries: 5
  rabbitmq:
    image: rabbitmq:3.12
    env_file:
      - .envs.production/rabbitmq/.env
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 2s
      timeout: 10s
      retries: 5
volumes:
  postgres_data:
