version: "3.9"
volumes:
  postgres_data:

name: hpds-production
services:
  front:
    image: kepins/hpds:front
    ports:
      - ${EXPOSE_PORT}:80
    depends_on:
      - apigateway

  apigateway:
    image: kepins/hpds:apigateway
    depends_on:
      rabbitmq:
        condition: service_healthy

  userservice:
    image: kepins/hpds:userservice
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  reservationservice:
    image: kepins/hpds:reservationservice
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  hotelservice:
    image: kepins/hpds:hotelservice
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  transportservice:
    image: kepins/hpds:transportservice
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  postgres:
    image: kepins/hpds:postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .envs/postgres/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d userservice_db"]
      interval: 2s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12
    env_file:
      - .envs/rabbitmq/.env
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 2s
      timeout: 10s
      retries: 5
