// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hotelservice.Models;

#nullable disable

namespace hotelservice.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hotelservice.Models.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("hotelservice.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FoodPricePerPerson")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1b56584-57d2-41da-82d0-3c6a7426db58"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 83m,
                            Name = "Pinea Resort & Spa",
                            Street = "Rruga e Dibres"
                        },
                        new
                        {
                            Id = new Guid("ca11b93a-9759-4cc3-aa96-7949ca8bf117"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 34m,
                            Name = "Diamma Resort",
                            Street = "Rruga Abdyl Frasheri"
                        },
                        new
                        {
                            Id = new Guid("c670897b-810b-44c8-93c3-1800a48bf7e8"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 31m,
                            Name = "Bonita Luxury Hotel",
                            Street = "Rruga Abdyl Frasheri"
                        },
                        new
                        {
                            Id = new Guid("540b1e5e-f3f8-4071-b755-78db5b80ceca"),
                            City = "Vlora",
                            Country = "albania",
                            FoodPricePerPerson = 90m,
                            Name = "Monte Carlo Vlora",
                            Street = "Rruga 28 Nentori"
                        },
                        new
                        {
                            Id = new Guid("b0a34988-a75d-4233-a843-3ac955980637"),
                            City = "Vlora",
                            Country = "albania",
                            FoodPricePerPerson = 99m,
                            Name = "MonteCarlo Lungomare",
                            Street = "Rruga e Kavajes"
                        },
                        new
                        {
                            Id = new Guid("1abf8993-caa1-415a-b5bd-22edb70e27c7"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 94m,
                            Name = "Mel Holidays",
                            Street = "Bulevardi Bajram Curri"
                        },
                        new
                        {
                            Id = new Guid("872e219e-2192-4a27-aef3-9aeba61055a1"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 74m,
                            Name = "Casa Durres",
                            Street = "Rruga e Dibres"
                        },
                        new
                        {
                            Id = new Guid("9f67336d-2292-4d17-b5f1-d1c1d01cae3b"),
                            City = "Chania",
                            Country = "grecja",
                            FoodPricePerPerson = 91m,
                            Name = "Rethymno Mare Water Park",
                            Street = "Leoforos Vasilissis Sofias"
                        },
                        new
                        {
                            Id = new Guid("9996c12e-3376-433b-9d0d-50818ff02fb4"),
                            City = "Peloponez",
                            Country = "grecja",
                            FoodPricePerPerson = 43m,
                            Name = "Aldemar Olympian Village",
                            Street = "Leoforos Alexandras"
                        },
                        new
                        {
                            Id = new Guid("b59bd50d-c9da-4baa-b0e8-b770f7c0b4c9"),
                            City = "Nero",
                            Country = "grecja",
                            FoodPricePerPerson = 56m,
                            Name = "Studia Katerina",
                            Street = "Leoforos Vasilissis Sofias"
                        },
                        new
                        {
                            Id = new Guid("6a6115ac-2851-4808-9b2a-e43a63d6c0a2"),
                            City = "Heraklion",
                            Country = "grecja",
                            FoodPricePerPerson = 74m,
                            Name = "Irini Studios",
                            Street = "Plateia Syntagmatos"
                        },
                        new
                        {
                            Id = new Guid("cfc1053f-749e-4433-a454-325f07593167"),
                            City = "Nero",
                            Country = "grecja",
                            FoodPricePerPerson = 110m,
                            Name = "Studia Maria",
                            Street = "Leoforos Alexandras"
                        },
                        new
                        {
                            Id = new Guid("6c0a406b-1d48-48f0-aad5-4fd2fb613641"),
                            City = "Olimpijska",
                            Country = "grecja",
                            FoodPricePerPerson = 31m,
                            Name = "Dias Apartments",
                            Street = "Plateia Syntagmatos"
                        },
                        new
                        {
                            Id = new Guid("6b572f55-21b2-468a-b7d1-0cdf182e15f2"),
                            City = "Marmaris",
                            Country = "turcja",
                            FoodPricePerPerson = 109m,
                            Name = "Turunc Resort",
                            Street = "Bağdat Caddesi"
                        },
                        new
                        {
                            Id = new Guid("c46ad161-cbc1-431e-8443-552d30a4b59d"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 111m,
                            Name = "Andriake Beach Club Hotel",
                            Street = "Atatürk Caddesi"
                        },
                        new
                        {
                            Id = new Guid("4357c674-758c-40b9-a37a-862cf404c9c8"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 114m,
                            Name = "Kimeros Park Holiday Village",
                            Street = "Bağdat Caddesi"
                        },
                        new
                        {
                            Id = new Guid("ebc1b138-1569-4f81-847e-687bc6d8f25d"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 35m,
                            Name = "Kleopatra Micador",
                            Street = "Atatürk Caddesi"
                        },
                        new
                        {
                            Id = new Guid("fa1ba4de-c45f-4f35-b8c2-59265f1c2e41"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 50m,
                            Name = "Melissa",
                            Street = "Halaskargazi Caddesi"
                        },
                        new
                        {
                            Id = new Guid("b9f1112d-59e6-484b-9e19-566f63a4538b"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 107m,
                            Name = "Kolibri Hotel",
                            Street = "Atatürk Caddesi"
                        },
                        new
                        {
                            Id = new Guid("e3f14182-c16d-4e34-8b6c-1b83a6d645a9"),
                            City = "Almeria",
                            Country = "hiszpania",
                            FoodPricePerPerson = 38m,
                            Name = "Evenia Zoraida Beach Resort",
                            Street = "Paseo del Prado"
                        },
                        new
                        {
                            Id = new Guid("d6304d95-c121-4b79-a77c-0cf69f83f331"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 96m,
                            Name = "Evenia Olympic Park",
                            Street = "Calle Mayor"
                        },
                        new
                        {
                            Id = new Guid("f7e3d8cc-f2f2-4abb-9c8a-cbf3da374901"),
                            City = "Luz",
                            Country = "hiszpania",
                            FoodPricePerPerson = 94m,
                            Name = "Estival Islantilla",
                            Street = "Calle Mayor"
                        },
                        new
                        {
                            Id = new Guid("96dab790-70c7-4d2f-9eee-d2623046b059"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 37m,
                            Name = "Cartago Nova by Alegria",
                            Street = "Paseo del Prado"
                        },
                        new
                        {
                            Id = new Guid("e432d88b-07d9-4f96-a53c-4cf74acad554"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 67m,
                            Name = "Catalonia",
                            Street = "Calle de Alcalá"
                        },
                        new
                        {
                            Id = new Guid("f426ae35-b432-412d-877b-e7b94801901a"),
                            City = "Maresme",
                            Country = "hiszpania",
                            FoodPricePerPerson = 106m,
                            Name = "Reymar Playa",
                            Street = "Paseo del Prado"
                        },
                        new
                        {
                            Id = new Guid("f52f8b0c-5ed6-4e4e-8958-5a5a3e4fafdb"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 77m,
                            Name = "GHT Oasis Park & Spa",
                            Street = "Gran Vía"
                        },
                        new
                        {
                            Id = new Guid("ae3f1cd0-7a0f-408f-958e-6443275e615c"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 79m,
                            Name = "San Domenico",
                            Street = "Via del Corso"
                        },
                        new
                        {
                            Id = new Guid("60df9ecd-6751-4703-b994-58521d544c82"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 47m,
                            Name = "Baia di Zambrone",
                            Street = "Via Veneto"
                        },
                        new
                        {
                            Id = new Guid("7a4dbe3f-bfb2-4ee1-89c5-1272ee9cef64"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 93m,
                            Name = "Rada Siri",
                            Street = "Via Veneto"
                        },
                        new
                        {
                            Id = new Guid("c7fc96fc-2cb0-4fa6-bed1-dd127eccaf25"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 81m,
                            Name = "Hotel Orizzonte Blu",
                            Street = "Via Nazionale"
                        },
                        new
                        {
                            Id = new Guid("18d18682-f9c6-44d2-8d00-c763d2923cc8"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 116m,
                            Name = "Gradac",
                            Street = "Kapucinska ulica"
                        },
                        new
                        {
                            Id = new Guid("e814608a-3793-489b-ba54-c0d55354de0d"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 31m,
                            Name = "Villa Penava",
                            Street = "Trg bana Josipa Jelačića"
                        },
                        new
                        {
                            Id = new Guid("bfea1f6f-f260-467b-a952-9b44e48462f8"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 42m,
                            Name = "Apartamenty Omiś",
                            Street = "Vukovarska ulica"
                        },
                        new
                        {
                            Id = new Guid("30708e68-aa83-489b-aeeb-12d03441fe78"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 88m,
                            Name = "Nano",
                            Street = "Maksimirska ulica"
                        },
                        new
                        {
                            Id = new Guid("f814655e-f6b3-4594-a144-e5f4c5ba9cc2"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 83m,
                            Name = "Apartamenty Makarska",
                            Street = "Maksimirska ulica"
                        },
                        new
                        {
                            Id = new Guid("a02d2882-9290-470b-9d0c-c2cadced8f17"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 97m,
                            Name = "Marina Resort Port Ghalib",
                            Street = "Sharia Tahrir"
                        },
                        new
                        {
                            Id = new Guid("fc6f8ccb-34bb-4dd6-8b40-615ad881f9f5"),
                            City = "Sheikh",
                            Country = "egipt",
                            FoodPricePerPerson = 76m,
                            Name = "Barcelo Tiran Sharm Resort",
                            Street = "Sharia Tahrir"
                        },
                        new
                        {
                            Id = new Guid("ac8be2a3-fd7b-4801-9201-5ade8eb5ca09"),
                            City = "Sheikh",
                            Country = "egipt",
                            FoodPricePerPerson = 74m,
                            Name = "Old Vic Resort Sharm",
                            Street = "Sharia Ramsis"
                        },
                        new
                        {
                            Id = new Guid("c7eac061-0015-45a5-b2f4-cd5d1b6bb88e"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 33m,
                            Name = "Marina Lodge Port Ghalib",
                            Street = "Sharia Ramsis"
                        },
                        new
                        {
                            Id = new Guid("bc609ca0-869c-4c8b-8c5b-5343a6bcea72"),
                            City = "Sheikh",
                            Country = "egipt",
                            FoodPricePerPerson = 116m,
                            Name = "Falcon Naama Star",
                            Street = "Sharia Salah Salem"
                        },
                        new
                        {
                            Id = new Guid("4333746e-41a6-420d-b54d-2d8659ad59cf"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 80m,
                            Name = "Protels Crystal Beach Resort",
                            Street = "Sharia Tahrir"
                        },
                        new
                        {
                            Id = new Guid("2b0c4a0b-c5b4-4383-9610-97323a80430c"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 89m,
                            Name = "MG Alexander The Great",
                            Street = "Sharia Gamal Abdel Nasser"
                        },
                        new
                        {
                            Id = new Guid("07742431-3af8-4f28-958d-1376cf478c7f"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 83m,
                            Name = "Bliss Nada Beach Resort",
                            Street = "Sharia Tahrir"
                        });
                });

            modelBuilder.Entity("hotelservice.Models.PopularHotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Counter")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PopularHotels");
                });

            modelBuilder.Entity("hotelservice.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("326b6f8e-c5c5-417d-a977-ba3e8e2fe1d8"),
                            Count = 3,
                            HotelId = new Guid("b1b56584-57d2-41da-82d0-3c6a7426db58"),
                            Price = 119m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("fea07654-5f06-496c-a24f-b08b48747100"),
                            Count = 2,
                            HotelId = new Guid("b1b56584-57d2-41da-82d0-3c6a7426db58"),
                            Price = 95m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("810854f2-62c3-46c7-8e6a-fa88ba070b8f"),
                            Count = 2,
                            HotelId = new Guid("b1b56584-57d2-41da-82d0-3c6a7426db58"),
                            Price = 123m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("cf932f47-b16d-485c-a67b-e762702f6fd6"),
                            Count = 2,
                            HotelId = new Guid("b1b56584-57d2-41da-82d0-3c6a7426db58"),
                            Price = 215m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("bc860757-dbaf-4d7a-a43c-ef7545c2527e"),
                            Count = 2,
                            HotelId = new Guid("ca11b93a-9759-4cc3-aa96-7949ca8bf117"),
                            Price = 145m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("ff80d8e9-f88a-49d5-b837-4fbd2f54f457"),
                            Count = 2,
                            HotelId = new Guid("ca11b93a-9759-4cc3-aa96-7949ca8bf117"),
                            Price = 138m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("d072e42f-c142-4a17-8f00-10aa74368e03"),
                            Count = 3,
                            HotelId = new Guid("ca11b93a-9759-4cc3-aa96-7949ca8bf117"),
                            Price = 74m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("6e175e74-7100-46f3-8fe0-4e7e9db01595"),
                            Count = 1,
                            HotelId = new Guid("ca11b93a-9759-4cc3-aa96-7949ca8bf117"),
                            Price = 205m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("fc30784c-a652-48e8-b209-d077a458f7e4"),
                            Count = 2,
                            HotelId = new Guid("c670897b-810b-44c8-93c3-1800a48bf7e8"),
                            Price = 186m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("0cab3bd0-99d6-4a96-a0f4-a35253e34452"),
                            Count = 3,
                            HotelId = new Guid("c670897b-810b-44c8-93c3-1800a48bf7e8"),
                            Price = 247m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("37c3b492-681f-4a25-acb3-8b21e70e5b8d"),
                            Count = 1,
                            HotelId = new Guid("c670897b-810b-44c8-93c3-1800a48bf7e8"),
                            Price = 164m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("f0ad56e7-1308-40d3-8820-e2d39d93a957"),
                            Count = 1,
                            HotelId = new Guid("c670897b-810b-44c8-93c3-1800a48bf7e8"),
                            Price = 69m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("c146dfca-0972-44af-97c2-d5dfa74164cf"),
                            Count = 1,
                            HotelId = new Guid("540b1e5e-f3f8-4071-b755-78db5b80ceca"),
                            Price = 84m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("1effeac6-addc-4b31-89cf-5dad3d51d351"),
                            Count = 3,
                            HotelId = new Guid("540b1e5e-f3f8-4071-b755-78db5b80ceca"),
                            Price = 147m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("9e6fe85f-ad1a-4046-b54f-f2062836e43d"),
                            Count = 2,
                            HotelId = new Guid("540b1e5e-f3f8-4071-b755-78db5b80ceca"),
                            Price = 78m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("d98c0e7a-8b7e-4e4e-9264-e4e6a8b3eb18"),
                            Count = 3,
                            HotelId = new Guid("540b1e5e-f3f8-4071-b755-78db5b80ceca"),
                            Price = 110m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("865bee79-82d4-4b6f-80ac-5064aef7d800"),
                            Count = 3,
                            HotelId = new Guid("b0a34988-a75d-4233-a843-3ac955980637"),
                            Price = 193m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("0e4a81bf-3026-407c-a81c-b42b9fc5871d"),
                            Count = 1,
                            HotelId = new Guid("b0a34988-a75d-4233-a843-3ac955980637"),
                            Price = 182m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("2b7da4a9-d035-41b8-88ad-b8e3a943e816"),
                            Count = 1,
                            HotelId = new Guid("b0a34988-a75d-4233-a843-3ac955980637"),
                            Price = 238m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("1b40a6d3-b384-4d59-b0e8-2203eb535732"),
                            Count = 3,
                            HotelId = new Guid("b0a34988-a75d-4233-a843-3ac955980637"),
                            Price = 70m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("b221589a-a1f2-4a33-b9cb-4a5e5183deef"),
                            Count = 3,
                            HotelId = new Guid("1abf8993-caa1-415a-b5bd-22edb70e27c7"),
                            Price = 219m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("02a86096-ab46-4804-b61e-0d1d22ae271b"),
                            Count = 3,
                            HotelId = new Guid("1abf8993-caa1-415a-b5bd-22edb70e27c7"),
                            Price = 109m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("78871ab0-f729-49e7-bc05-e7e3acbebce3"),
                            Count = 3,
                            HotelId = new Guid("1abf8993-caa1-415a-b5bd-22edb70e27c7"),
                            Price = 78m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("9aa21c45-69f3-43e8-a25e-eaff9147dcc1"),
                            Count = 2,
                            HotelId = new Guid("1abf8993-caa1-415a-b5bd-22edb70e27c7"),
                            Price = 143m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("875d96ab-c397-4de8-8fe4-fa664aa4b2c9"),
                            Count = 3,
                            HotelId = new Guid("872e219e-2192-4a27-aef3-9aeba61055a1"),
                            Price = 104m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("cf03720a-a0ea-4179-ab26-b56cfd522958"),
                            Count = 1,
                            HotelId = new Guid("872e219e-2192-4a27-aef3-9aeba61055a1"),
                            Price = 136m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("8eeb6173-a165-49e0-b8b2-b10228fc1f2d"),
                            Count = 3,
                            HotelId = new Guid("872e219e-2192-4a27-aef3-9aeba61055a1"),
                            Price = 177m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("36a71b2e-4bb7-41a8-b8db-93d9c352e9b1"),
                            Count = 2,
                            HotelId = new Guid("872e219e-2192-4a27-aef3-9aeba61055a1"),
                            Price = 105m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("18795135-0209-4630-80f3-5dfc2394d136"),
                            Count = 2,
                            HotelId = new Guid("9f67336d-2292-4d17-b5f1-d1c1d01cae3b"),
                            Price = 211m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("74d817db-a7f3-459d-b991-50190450a0d9"),
                            Count = 1,
                            HotelId = new Guid("9f67336d-2292-4d17-b5f1-d1c1d01cae3b"),
                            Price = 77m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("7cbef198-a92b-4d95-b9b8-b1f04b9b8d71"),
                            Count = 2,
                            HotelId = new Guid("9f67336d-2292-4d17-b5f1-d1c1d01cae3b"),
                            Price = 169m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("bd2b8859-904c-485d-8e9a-0433edae1cd7"),
                            Count = 1,
                            HotelId = new Guid("9f67336d-2292-4d17-b5f1-d1c1d01cae3b"),
                            Price = 84m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("ce76d8f3-bb46-46ce-81a4-176866b70326"),
                            Count = 2,
                            HotelId = new Guid("9996c12e-3376-433b-9d0d-50818ff02fb4"),
                            Price = 239m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("13d5dc6d-6150-4137-a4a7-ee1af65d4c2e"),
                            Count = 3,
                            HotelId = new Guid("9996c12e-3376-433b-9d0d-50818ff02fb4"),
                            Price = 208m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("f982a5e5-4466-4e22-9a4c-7b3a761f1420"),
                            Count = 3,
                            HotelId = new Guid("9996c12e-3376-433b-9d0d-50818ff02fb4"),
                            Price = 161m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("ce7d6e52-a572-4071-bbf9-017f55c8ac58"),
                            Count = 1,
                            HotelId = new Guid("9996c12e-3376-433b-9d0d-50818ff02fb4"),
                            Price = 64m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("64e04704-3515-447e-b14c-76503a7ae6af"),
                            Count = 1,
                            HotelId = new Guid("b59bd50d-c9da-4baa-b0e8-b770f7c0b4c9"),
                            Price = 129m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("80dcf4ff-1a22-4f5c-ab55-4f4a7b90ce87"),
                            Count = 2,
                            HotelId = new Guid("b59bd50d-c9da-4baa-b0e8-b770f7c0b4c9"),
                            Price = 234m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("046ed853-3820-4aa5-93c2-d34ca12e3f9e"),
                            Count = 3,
                            HotelId = new Guid("b59bd50d-c9da-4baa-b0e8-b770f7c0b4c9"),
                            Price = 84m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("e4b9a719-dc4d-4fe7-b497-42d2da56d2f7"),
                            Count = 3,
                            HotelId = new Guid("b59bd50d-c9da-4baa-b0e8-b770f7c0b4c9"),
                            Price = 216m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("7c5abe66-f217-461f-b99f-e50485678fcb"),
                            Count = 2,
                            HotelId = new Guid("6a6115ac-2851-4808-9b2a-e43a63d6c0a2"),
                            Price = 165m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("61ddc3ae-ab82-4d1a-8daf-46a8cb60962e"),
                            Count = 2,
                            HotelId = new Guid("6a6115ac-2851-4808-9b2a-e43a63d6c0a2"),
                            Price = 88m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("353795a3-02eb-4176-aa87-2f0e7138cc44"),
                            Count = 1,
                            HotelId = new Guid("6a6115ac-2851-4808-9b2a-e43a63d6c0a2"),
                            Price = 210m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("fbf27c82-a896-43f5-bfba-f834827f4ad4"),
                            Count = 1,
                            HotelId = new Guid("6a6115ac-2851-4808-9b2a-e43a63d6c0a2"),
                            Price = 119m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("3d04f924-524b-4ece-a96f-1befe9c4873a"),
                            Count = 1,
                            HotelId = new Guid("cfc1053f-749e-4433-a454-325f07593167"),
                            Price = 130m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("d1969e5d-a0ea-4b57-8f77-4bed66195125"),
                            Count = 3,
                            HotelId = new Guid("cfc1053f-749e-4433-a454-325f07593167"),
                            Price = 97m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("e433567b-baed-49ac-bf24-b711dd8f6df5"),
                            Count = 3,
                            HotelId = new Guid("cfc1053f-749e-4433-a454-325f07593167"),
                            Price = 165m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("c65a3afe-9222-4eb9-8ae4-f1f291dfa2df"),
                            Count = 1,
                            HotelId = new Guid("cfc1053f-749e-4433-a454-325f07593167"),
                            Price = 72m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("a5e82d93-e441-4e96-bb59-fb602d3f7468"),
                            Count = 1,
                            HotelId = new Guid("6c0a406b-1d48-48f0-aad5-4fd2fb613641"),
                            Price = 153m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("c24679bb-1311-4416-8e67-0470bc96d394"),
                            Count = 2,
                            HotelId = new Guid("6c0a406b-1d48-48f0-aad5-4fd2fb613641"),
                            Price = 125m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("0339d81a-ab92-439f-9a35-12b0b84cb77a"),
                            Count = 1,
                            HotelId = new Guid("6c0a406b-1d48-48f0-aad5-4fd2fb613641"),
                            Price = 183m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("88270b20-2ade-4e6f-bc09-1520261a65d1"),
                            Count = 1,
                            HotelId = new Guid("6c0a406b-1d48-48f0-aad5-4fd2fb613641"),
                            Price = 84m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("5b417da4-53f3-49d7-a791-529aaa16a74b"),
                            Count = 2,
                            HotelId = new Guid("6b572f55-21b2-468a-b7d1-0cdf182e15f2"),
                            Price = 207m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("fccba2a8-53e0-435d-9957-23c673c1b555"),
                            Count = 3,
                            HotelId = new Guid("6b572f55-21b2-468a-b7d1-0cdf182e15f2"),
                            Price = 131m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("2da54ee3-fdad-4ff9-a9b7-a4d83be78637"),
                            Count = 3,
                            HotelId = new Guid("6b572f55-21b2-468a-b7d1-0cdf182e15f2"),
                            Price = 146m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("a32d60d4-c8fd-4a76-a24b-cedb359b8416"),
                            Count = 1,
                            HotelId = new Guid("6b572f55-21b2-468a-b7d1-0cdf182e15f2"),
                            Price = 119m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("4966bfe6-2234-44cc-b62c-df7deef03941"),
                            Count = 3,
                            HotelId = new Guid("c46ad161-cbc1-431e-8443-552d30a4b59d"),
                            Price = 132m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("1e839581-f716-425a-97fc-1885f4133290"),
                            Count = 2,
                            HotelId = new Guid("c46ad161-cbc1-431e-8443-552d30a4b59d"),
                            Price = 244m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("8b6ac292-5ddf-4a52-996f-fc45ecc91fb7"),
                            Count = 1,
                            HotelId = new Guid("c46ad161-cbc1-431e-8443-552d30a4b59d"),
                            Price = 243m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("ab612248-34dd-4f85-9b5e-1abdfec51229"),
                            Count = 2,
                            HotelId = new Guid("c46ad161-cbc1-431e-8443-552d30a4b59d"),
                            Price = 111m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("0dbde87e-6541-49cb-a68f-c46032f80292"),
                            Count = 3,
                            HotelId = new Guid("4357c674-758c-40b9-a37a-862cf404c9c8"),
                            Price = 148m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("36673e3b-3726-497b-b1ad-fe58429de6be"),
                            Count = 2,
                            HotelId = new Guid("4357c674-758c-40b9-a37a-862cf404c9c8"),
                            Price = 168m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("8e25960b-f8ee-48c2-94d4-c5d9338fcf33"),
                            Count = 3,
                            HotelId = new Guid("4357c674-758c-40b9-a37a-862cf404c9c8"),
                            Price = 230m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("0a924d9f-aab0-4df2-827f-acccfd857017"),
                            Count = 3,
                            HotelId = new Guid("4357c674-758c-40b9-a37a-862cf404c9c8"),
                            Price = 111m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("146c9afc-31cf-42b5-9e3e-ed1c65afe2a5"),
                            Count = 1,
                            HotelId = new Guid("ebc1b138-1569-4f81-847e-687bc6d8f25d"),
                            Price = 201m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("1a14f0d0-fa9e-4d8a-b429-dc0e825a3c7f"),
                            Count = 2,
                            HotelId = new Guid("ebc1b138-1569-4f81-847e-687bc6d8f25d"),
                            Price = 219m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("a9a65a09-762b-490f-9d83-ccc2fbce1702"),
                            Count = 2,
                            HotelId = new Guid("ebc1b138-1569-4f81-847e-687bc6d8f25d"),
                            Price = 76m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("4d93abfe-134f-40f6-b395-84b8bf30a3c7"),
                            Count = 1,
                            HotelId = new Guid("ebc1b138-1569-4f81-847e-687bc6d8f25d"),
                            Price = 63m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("0e717d69-49c8-46ff-b8fe-ad74024fa5ad"),
                            Count = 1,
                            HotelId = new Guid("fa1ba4de-c45f-4f35-b8c2-59265f1c2e41"),
                            Price = 175m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("dea7278d-ee1a-4ea1-b3e7-b7998d86b501"),
                            Count = 1,
                            HotelId = new Guid("fa1ba4de-c45f-4f35-b8c2-59265f1c2e41"),
                            Price = 245m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("242b361e-9897-4e81-afad-25f6541cc797"),
                            Count = 1,
                            HotelId = new Guid("fa1ba4de-c45f-4f35-b8c2-59265f1c2e41"),
                            Price = 50m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("881e4028-06fb-43f3-a4ed-f27272cbfd67"),
                            Count = 1,
                            HotelId = new Guid("fa1ba4de-c45f-4f35-b8c2-59265f1c2e41"),
                            Price = 219m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("0fea3546-5f60-494a-9d6a-a021ecfbf82b"),
                            Count = 3,
                            HotelId = new Guid("b9f1112d-59e6-484b-9e19-566f63a4538b"),
                            Price = 215m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("ee82b456-b465-40c7-bb44-7becdbcaf7e3"),
                            Count = 1,
                            HotelId = new Guid("b9f1112d-59e6-484b-9e19-566f63a4538b"),
                            Price = 164m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("91855397-3d20-4c7d-8502-32af04ba28ed"),
                            Count = 3,
                            HotelId = new Guid("b9f1112d-59e6-484b-9e19-566f63a4538b"),
                            Price = 163m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("1074a570-093e-4c80-a381-ae7c9abf8a50"),
                            Count = 2,
                            HotelId = new Guid("b9f1112d-59e6-484b-9e19-566f63a4538b"),
                            Price = 247m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("d895973e-21e5-41bd-bb9b-16bb97cb9678"),
                            Count = 1,
                            HotelId = new Guid("e3f14182-c16d-4e34-8b6c-1b83a6d645a9"),
                            Price = 76m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("bdb8b8c0-8e4d-422b-8150-6ab5cbcf8bcc"),
                            Count = 3,
                            HotelId = new Guid("e3f14182-c16d-4e34-8b6c-1b83a6d645a9"),
                            Price = 149m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("23361e48-020e-4941-9042-06c06de1eef4"),
                            Count = 3,
                            HotelId = new Guid("e3f14182-c16d-4e34-8b6c-1b83a6d645a9"),
                            Price = 197m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("57fe9bf9-d2ce-44c5-b5c3-0b3cc92e3301"),
                            Count = 2,
                            HotelId = new Guid("e3f14182-c16d-4e34-8b6c-1b83a6d645a9"),
                            Price = 237m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("5311755b-7c1d-4ab7-97d5-20779a881887"),
                            Count = 2,
                            HotelId = new Guid("d6304d95-c121-4b79-a77c-0cf69f83f331"),
                            Price = 87m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("1c9c5d2d-e662-476d-abcb-0909e33ae679"),
                            Count = 1,
                            HotelId = new Guid("d6304d95-c121-4b79-a77c-0cf69f83f331"),
                            Price = 247m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("339dbe64-3ca2-441c-b1d5-79502938a058"),
                            Count = 3,
                            HotelId = new Guid("d6304d95-c121-4b79-a77c-0cf69f83f331"),
                            Price = 70m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("c8002d53-f8e7-42ef-bcaa-99111e6ffb8c"),
                            Count = 3,
                            HotelId = new Guid("d6304d95-c121-4b79-a77c-0cf69f83f331"),
                            Price = 184m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("627602d2-2269-4c84-818a-2294e00618fa"),
                            Count = 3,
                            HotelId = new Guid("f7e3d8cc-f2f2-4abb-9c8a-cbf3da374901"),
                            Price = 242m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("e5282cfe-045b-48b9-937a-3f200e6b3975"),
                            Count = 1,
                            HotelId = new Guid("f7e3d8cc-f2f2-4abb-9c8a-cbf3da374901"),
                            Price = 132m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("8efb1152-b2eb-407c-91af-da5bab63e3df"),
                            Count = 3,
                            HotelId = new Guid("f7e3d8cc-f2f2-4abb-9c8a-cbf3da374901"),
                            Price = 142m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("90bb4c84-a45b-43d2-8213-be3bb8041a17"),
                            Count = 2,
                            HotelId = new Guid("f7e3d8cc-f2f2-4abb-9c8a-cbf3da374901"),
                            Price = 154m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("a645e444-f78a-41fb-bedc-f5ec6440ab12"),
                            Count = 3,
                            HotelId = new Guid("96dab790-70c7-4d2f-9eee-d2623046b059"),
                            Price = 233m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("30671c9b-0822-4138-9cc6-8fa30973edab"),
                            Count = 3,
                            HotelId = new Guid("96dab790-70c7-4d2f-9eee-d2623046b059"),
                            Price = 204m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("f5d0b386-d6e3-4ddc-9ff1-9a2e4d08668d"),
                            Count = 1,
                            HotelId = new Guid("96dab790-70c7-4d2f-9eee-d2623046b059"),
                            Price = 171m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("7935aeb6-0764-46e2-bfed-305e62d0609e"),
                            Count = 1,
                            HotelId = new Guid("96dab790-70c7-4d2f-9eee-d2623046b059"),
                            Price = 94m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("589f072f-de7b-4b74-a368-ed5b87381c5d"),
                            Count = 1,
                            HotelId = new Guid("e432d88b-07d9-4f96-a53c-4cf74acad554"),
                            Price = 53m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("0fd4b9fa-6862-42c5-b597-1d313ff70e89"),
                            Count = 3,
                            HotelId = new Guid("e432d88b-07d9-4f96-a53c-4cf74acad554"),
                            Price = 92m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("c619eb55-236c-4f1f-becb-3bbba88d83e5"),
                            Count = 3,
                            HotelId = new Guid("e432d88b-07d9-4f96-a53c-4cf74acad554"),
                            Price = 250m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("17d79a23-db84-454a-85f4-f22d17b8d76c"),
                            Count = 3,
                            HotelId = new Guid("e432d88b-07d9-4f96-a53c-4cf74acad554"),
                            Price = 241m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("3b808083-0d1f-4671-95d8-c98f9c0a05f8"),
                            Count = 3,
                            HotelId = new Guid("f426ae35-b432-412d-877b-e7b94801901a"),
                            Price = 190m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("2c4255f8-dcce-4d43-baea-03f8e1dcc5a0"),
                            Count = 1,
                            HotelId = new Guid("f426ae35-b432-412d-877b-e7b94801901a"),
                            Price = 112m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("e3313e2b-35ab-4bd0-9822-467c899351fc"),
                            Count = 2,
                            HotelId = new Guid("f426ae35-b432-412d-877b-e7b94801901a"),
                            Price = 152m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("e384fd8f-4cd4-4c8f-a88f-85b0d8b77c2a"),
                            Count = 1,
                            HotelId = new Guid("f426ae35-b432-412d-877b-e7b94801901a"),
                            Price = 177m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("84e085e4-d6e5-4ea7-aea0-f56922cb7c9d"),
                            Count = 2,
                            HotelId = new Guid("f52f8b0c-5ed6-4e4e-8958-5a5a3e4fafdb"),
                            Price = 60m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("0e02726e-50b3-45eb-81e2-d3b8a13411a4"),
                            Count = 3,
                            HotelId = new Guid("f52f8b0c-5ed6-4e4e-8958-5a5a3e4fafdb"),
                            Price = 190m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("22100842-76b4-4648-8533-1bf1c4a22d9c"),
                            Count = 3,
                            HotelId = new Guid("f52f8b0c-5ed6-4e4e-8958-5a5a3e4fafdb"),
                            Price = 77m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("17a9f3a8-d3ee-4ce5-9c0d-68590328103d"),
                            Count = 3,
                            HotelId = new Guid("f52f8b0c-5ed6-4e4e-8958-5a5a3e4fafdb"),
                            Price = 217m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("b4ac7f4e-836e-4939-ad18-cfdf62e0b55c"),
                            Count = 1,
                            HotelId = new Guid("ae3f1cd0-7a0f-408f-958e-6443275e615c"),
                            Price = 146m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("5de97438-0943-48ee-9288-ce2550b2a0e5"),
                            Count = 3,
                            HotelId = new Guid("ae3f1cd0-7a0f-408f-958e-6443275e615c"),
                            Price = 107m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("9248f074-3f97-46f8-ae50-a6efa4a1a106"),
                            Count = 1,
                            HotelId = new Guid("ae3f1cd0-7a0f-408f-958e-6443275e615c"),
                            Price = 164m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("7b0d02c9-62d5-4d0a-bfd2-7efd346a5c89"),
                            Count = 3,
                            HotelId = new Guid("ae3f1cd0-7a0f-408f-958e-6443275e615c"),
                            Price = 162m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("5e393c79-4674-4855-8dde-713a9c5ca394"),
                            Count = 2,
                            HotelId = new Guid("60df9ecd-6751-4703-b994-58521d544c82"),
                            Price = 213m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("acbf6628-5989-44d4-962a-ff918826d97e"),
                            Count = 2,
                            HotelId = new Guid("60df9ecd-6751-4703-b994-58521d544c82"),
                            Price = 131m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("faf2d93d-4a66-402d-a099-f7dd4591c18a"),
                            Count = 2,
                            HotelId = new Guid("60df9ecd-6751-4703-b994-58521d544c82"),
                            Price = 140m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("ff338b3b-f01b-49d0-904a-7851c38bff83"),
                            Count = 2,
                            HotelId = new Guid("60df9ecd-6751-4703-b994-58521d544c82"),
                            Price = 250m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("76bd82b7-2f21-486c-871e-2a98c98bf911"),
                            Count = 3,
                            HotelId = new Guid("7a4dbe3f-bfb2-4ee1-89c5-1272ee9cef64"),
                            Price = 178m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("1326b48a-7603-4e0e-8cd9-40aa9949752e"),
                            Count = 3,
                            HotelId = new Guid("7a4dbe3f-bfb2-4ee1-89c5-1272ee9cef64"),
                            Price = 216m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("5218c2f3-4650-426f-92ea-4776d224e832"),
                            Count = 1,
                            HotelId = new Guid("7a4dbe3f-bfb2-4ee1-89c5-1272ee9cef64"),
                            Price = 98m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("78367c7d-5e0c-4927-854e-4974ffe7b3f7"),
                            Count = 3,
                            HotelId = new Guid("7a4dbe3f-bfb2-4ee1-89c5-1272ee9cef64"),
                            Price = 165m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("429ec3ea-f9f6-4bb0-ada5-4241ef617f6e"),
                            Count = 3,
                            HotelId = new Guid("c7fc96fc-2cb0-4fa6-bed1-dd127eccaf25"),
                            Price = 118m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("2e81afda-bff4-4ec7-bec9-789b10294902"),
                            Count = 2,
                            HotelId = new Guid("c7fc96fc-2cb0-4fa6-bed1-dd127eccaf25"),
                            Price = 73m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("e66f6ca2-681e-4bf7-b630-ad0316576fdb"),
                            Count = 1,
                            HotelId = new Guid("c7fc96fc-2cb0-4fa6-bed1-dd127eccaf25"),
                            Price = 166m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("714dbc1f-0579-4575-bc3a-3669dd733926"),
                            Count = 2,
                            HotelId = new Guid("c7fc96fc-2cb0-4fa6-bed1-dd127eccaf25"),
                            Price = 81m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("75f9c47d-ecd2-4ae1-b6fc-70f65c56c3e7"),
                            Count = 2,
                            HotelId = new Guid("18d18682-f9c6-44d2-8d00-c763d2923cc8"),
                            Price = 111m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("38803583-132c-4337-91cd-dfd2cf646616"),
                            Count = 1,
                            HotelId = new Guid("18d18682-f9c6-44d2-8d00-c763d2923cc8"),
                            Price = 110m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("4b959c68-607d-4765-add3-866c13a0816a"),
                            Count = 1,
                            HotelId = new Guid("18d18682-f9c6-44d2-8d00-c763d2923cc8"),
                            Price = 95m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("c2464b1a-4047-4e4e-9314-70101ac4800b"),
                            Count = 3,
                            HotelId = new Guid("18d18682-f9c6-44d2-8d00-c763d2923cc8"),
                            Price = 239m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("a5eadc38-5480-4355-86ed-df55620c84ef"),
                            Count = 1,
                            HotelId = new Guid("e814608a-3793-489b-ba54-c0d55354de0d"),
                            Price = 121m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("3a2d0b21-1ebd-46f4-95ba-b73c0801f4a8"),
                            Count = 1,
                            HotelId = new Guid("e814608a-3793-489b-ba54-c0d55354de0d"),
                            Price = 187m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("1e9a14cf-26d3-4939-9763-90f0b04e5e67"),
                            Count = 2,
                            HotelId = new Guid("e814608a-3793-489b-ba54-c0d55354de0d"),
                            Price = 201m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("29fedea0-919c-40e2-b1ff-c5494da6f595"),
                            Count = 1,
                            HotelId = new Guid("e814608a-3793-489b-ba54-c0d55354de0d"),
                            Price = 73m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("b19afdf0-e77f-4f8b-bd8a-895001445ddd"),
                            Count = 3,
                            HotelId = new Guid("bfea1f6f-f260-467b-a952-9b44e48462f8"),
                            Price = 84m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("3109e80a-87f5-4205-8039-5c434c960a12"),
                            Count = 1,
                            HotelId = new Guid("bfea1f6f-f260-467b-a952-9b44e48462f8"),
                            Price = 145m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("10fed4b1-4638-427b-af64-bc92dd6ca59c"),
                            Count = 2,
                            HotelId = new Guid("bfea1f6f-f260-467b-a952-9b44e48462f8"),
                            Price = 221m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("7db4a46e-6b62-4197-9375-46448665b0a2"),
                            Count = 2,
                            HotelId = new Guid("bfea1f6f-f260-467b-a952-9b44e48462f8"),
                            Price = 108m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("4f612483-2055-47a1-bbf5-bfa01290b6dc"),
                            Count = 2,
                            HotelId = new Guid("30708e68-aa83-489b-aeeb-12d03441fe78"),
                            Price = 220m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("6db493bf-2576-4495-8108-5204e40d70b7"),
                            Count = 2,
                            HotelId = new Guid("30708e68-aa83-489b-aeeb-12d03441fe78"),
                            Price = 96m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("528735f6-224b-4565-b49b-f15f01f4115e"),
                            Count = 1,
                            HotelId = new Guid("30708e68-aa83-489b-aeeb-12d03441fe78"),
                            Price = 143m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("6b9dbc6d-0674-4d4b-b0b6-60eefab05729"),
                            Count = 3,
                            HotelId = new Guid("30708e68-aa83-489b-aeeb-12d03441fe78"),
                            Price = 71m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("b4dea72e-4980-4b4d-bc36-f7c0e22cb71c"),
                            Count = 2,
                            HotelId = new Guid("f814655e-f6b3-4594-a144-e5f4c5ba9cc2"),
                            Price = 179m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("389766fe-5df5-42a8-90c9-46aa7081758d"),
                            Count = 3,
                            HotelId = new Guid("f814655e-f6b3-4594-a144-e5f4c5ba9cc2"),
                            Price = 155m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("e8c6a664-0f47-4a94-a05e-b2175b977ef4"),
                            Count = 1,
                            HotelId = new Guid("f814655e-f6b3-4594-a144-e5f4c5ba9cc2"),
                            Price = 177m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("dca50e7a-3f40-4e70-b69b-a1d54bbdc0ae"),
                            Count = 1,
                            HotelId = new Guid("f814655e-f6b3-4594-a144-e5f4c5ba9cc2"),
                            Price = 195m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("97f9eb7a-4d07-46f5-a889-39fe1986ba6f"),
                            Count = 2,
                            HotelId = new Guid("a02d2882-9290-470b-9d0c-c2cadced8f17"),
                            Price = 76m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("af36dc3a-9a82-4f8c-827d-e4c23870db64"),
                            Count = 3,
                            HotelId = new Guid("a02d2882-9290-470b-9d0c-c2cadced8f17"),
                            Price = 195m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("4a1b2a20-1c57-466c-a3f0-91d60c994450"),
                            Count = 3,
                            HotelId = new Guid("a02d2882-9290-470b-9d0c-c2cadced8f17"),
                            Price = 180m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("f5feedb9-cbbd-40a1-aa90-7ed2fa0c4fa7"),
                            Count = 3,
                            HotelId = new Guid("a02d2882-9290-470b-9d0c-c2cadced8f17"),
                            Price = 210m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("6b6ca043-9ef2-48e2-ab32-8a117118b184"),
                            Count = 2,
                            HotelId = new Guid("fc6f8ccb-34bb-4dd6-8b40-615ad881f9f5"),
                            Price = 153m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("ed271d94-ba7e-4cc5-bc04-20b456b67864"),
                            Count = 2,
                            HotelId = new Guid("fc6f8ccb-34bb-4dd6-8b40-615ad881f9f5"),
                            Price = 221m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("c8857e1f-7e88-4b67-948d-6aa4ab032b6d"),
                            Count = 3,
                            HotelId = new Guid("fc6f8ccb-34bb-4dd6-8b40-615ad881f9f5"),
                            Price = 223m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("ab9b2886-b3bc-4cbf-aa56-277c1c9ebdb1"),
                            Count = 3,
                            HotelId = new Guid("fc6f8ccb-34bb-4dd6-8b40-615ad881f9f5"),
                            Price = 135m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("e090cedc-dcec-4e85-a4fd-bcb0d5fab136"),
                            Count = 2,
                            HotelId = new Guid("ac8be2a3-fd7b-4801-9201-5ade8eb5ca09"),
                            Price = 66m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("8a2b81e4-365b-45f6-9d61-ac7ee05e70fa"),
                            Count = 2,
                            HotelId = new Guid("ac8be2a3-fd7b-4801-9201-5ade8eb5ca09"),
                            Price = 179m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("51be6085-8310-47f7-a249-9fc099a4810a"),
                            Count = 2,
                            HotelId = new Guid("ac8be2a3-fd7b-4801-9201-5ade8eb5ca09"),
                            Price = 125m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("2e9a84bf-2c0c-4005-a10f-685215bd8b39"),
                            Count = 2,
                            HotelId = new Guid("ac8be2a3-fd7b-4801-9201-5ade8eb5ca09"),
                            Price = 147m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("6153ed60-b7e5-4289-8b0e-5a8278b58d4e"),
                            Count = 2,
                            HotelId = new Guid("c7eac061-0015-45a5-b2f4-cd5d1b6bb88e"),
                            Price = 176m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("c24b2ae0-43bf-4305-ae8b-6b8b95e6e8b8"),
                            Count = 3,
                            HotelId = new Guid("c7eac061-0015-45a5-b2f4-cd5d1b6bb88e"),
                            Price = 95m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("dcbd9103-b5f3-44f2-ab62-9703940572b8"),
                            Count = 3,
                            HotelId = new Guid("c7eac061-0015-45a5-b2f4-cd5d1b6bb88e"),
                            Price = 127m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("e4bdab06-ebce-452c-af61-754bcab579ab"),
                            Count = 3,
                            HotelId = new Guid("c7eac061-0015-45a5-b2f4-cd5d1b6bb88e"),
                            Price = 88m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("1286e853-7c3f-48f0-8b1e-af0497f940c7"),
                            Count = 1,
                            HotelId = new Guid("bc609ca0-869c-4c8b-8c5b-5343a6bcea72"),
                            Price = 158m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("c8fab056-f713-47ab-948d-9871feb33054"),
                            Count = 2,
                            HotelId = new Guid("bc609ca0-869c-4c8b-8c5b-5343a6bcea72"),
                            Price = 133m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("2a983e6b-977c-47d4-ba34-e4cd7f3bbb97"),
                            Count = 3,
                            HotelId = new Guid("bc609ca0-869c-4c8b-8c5b-5343a6bcea72"),
                            Price = 95m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("1ae11319-8ee5-4d11-bf51-6fee8e352b87"),
                            Count = 3,
                            HotelId = new Guid("bc609ca0-869c-4c8b-8c5b-5343a6bcea72"),
                            Price = 154m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("2f576f86-3e98-4951-aab8-1b532462497f"),
                            Count = 3,
                            HotelId = new Guid("4333746e-41a6-420d-b54d-2d8659ad59cf"),
                            Price = 129m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("c0ef69e9-3065-4663-b2e4-84a3ef98a7d1"),
                            Count = 2,
                            HotelId = new Guid("4333746e-41a6-420d-b54d-2d8659ad59cf"),
                            Price = 62m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("1cc47ecc-3399-4baf-9856-62a2037cd419"),
                            Count = 2,
                            HotelId = new Guid("4333746e-41a6-420d-b54d-2d8659ad59cf"),
                            Price = 162m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("bc507cb2-9722-4495-a215-3a0a2f219df7"),
                            Count = 3,
                            HotelId = new Guid("4333746e-41a6-420d-b54d-2d8659ad59cf"),
                            Price = 191m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("d3df3a6f-cb3c-4014-82eb-90e034ed055a"),
                            Count = 2,
                            HotelId = new Guid("2b0c4a0b-c5b4-4383-9610-97323a80430c"),
                            Price = 188m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("d8c016f3-5b27-41f5-a80f-d35be8833c76"),
                            Count = 2,
                            HotelId = new Guid("2b0c4a0b-c5b4-4383-9610-97323a80430c"),
                            Price = 90m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("ed63ba28-299a-43a1-a064-30c0843961e6"),
                            Count = 2,
                            HotelId = new Guid("2b0c4a0b-c5b4-4383-9610-97323a80430c"),
                            Price = 166m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("c2a265df-2b81-4080-ad4c-3e3f42a3ca77"),
                            Count = 2,
                            HotelId = new Guid("2b0c4a0b-c5b4-4383-9610-97323a80430c"),
                            Price = 209m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("be088051-f09b-4b90-a53a-d4818a0fcf75"),
                            Count = 1,
                            HotelId = new Guid("07742431-3af8-4f28-958d-1376cf478c7f"),
                            Price = 123m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("d5c334c6-3d47-4c41-995f-0ff51be6804b"),
                            Count = 1,
                            HotelId = new Guid("07742431-3af8-4f28-958d-1376cf478c7f"),
                            Price = 219m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("55b5d7a9-b2b3-4785-8ec0-6d47c963aeeb"),
                            Count = 1,
                            HotelId = new Guid("07742431-3af8-4f28-958d-1376cf478c7f"),
                            Price = 218m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("b81be36f-76b0-4cae-8a21-81d27a4a2432"),
                            Count = 1,
                            HotelId = new Guid("07742431-3af8-4f28-958d-1376cf478c7f"),
                            Price = 235m,
                            Size = 5
                        });
                });

            modelBuilder.Entity("hotelservice.Models.RoomReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomsId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoomsReserved")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomsId");

                    b.ToTable("RoomReservations");
                });

            modelBuilder.Entity("hotelservice.Models.Discount", b =>
                {
                    b.HasOne("hotelservice.Models.Hotel", null)
                        .WithMany("Discounts")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hotelservice.Models.Room", b =>
                {
                    b.HasOne("hotelservice.Models.Hotel", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hotelservice.Models.RoomReservation", b =>
                {
                    b.HasOne("hotelservice.Models.Room", null)
                        .WithMany("Bookings")
                        .HasForeignKey("RoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hotelservice.Models.Hotel", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("hotelservice.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
