name: Deliver released image

on:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Echo Git Tag
        id: git_tag
        run: echo ${{ github.event.release.tag_name }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsww_184297_apigateway -f apigateway/Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsww_184297_userservice -f userservice/Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsww_184297_reservationservice -f reservationservice/Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsww_184297_hotelservice -f hotelservice/Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsww_184297_transportservice -f transportservice/Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsww_184297_postgres -f postgres/Dockerfile .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/rsww_184297_apigateway
          docker push ${{ secrets.DOCKER_USERNAME }}/rsww_184297_userservice
          docker push ${{ secrets.DOCKER_USERNAME }}/rsww_184297_reservationservice
          docker push ${{ secrets.DOCKER_USERNAME }}/rsww_184297_hotelservice
          docker push ${{ secrets.DOCKER_USERNAME }}/rsww_184297_transportservice
          docker push ${{ secrets.DOCKER_USERNAME }}/rsww_184297_postgres
          
